# Project information
site_name: FunQL .NET
site_description: API Query Library
site_author: Xtracked
site_url: https://dotnet.funql.io/

# Repository
repo_url: https://github.com/funql/funql-dotnet
edit_uri: blob/main/docs/

# Copyright
copyright: >-
  Copyright &copy; 2025 Xtracked |
  <a href="https://www.xtracked.com/privacy-policy/" target="_blank" rel="noopener">Privacy policy</a>

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: teal
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: teal
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - toc.follow
  font:
    text: Roboto
    code: JetBrains Mono
  logo: assets/icon.png
  favicon: assets/favicon.png

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: funql/funql-dotnet
      branch: main

# Additional configuration
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/funql

# Additional CSS
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

# Page tree
nav:
  - Introduction: index.md
  - Getting started: getting-started.md
  - Defining a schema:
    - defining-a-schema/index.md
    - Features: defining-a-schema/features.md
    - Requests: defining-a-schema/requests.md
    - Parameters: defining-a-schema/parameters.md
    - Fields: defining-a-schema/fields.md
  - Executing queries:
    - executing-queries/index.md
    - Execution pipeline: executing-queries/pipeline.md
  - Integrations:
    - integrations/index.md
    - Entity Framework: integrations/efcore.md
    - NodaTime: integrations/nodatime.md
    - Newtonsoft.Json: integrations/newtonsoftjson.md
  - Examples:
    - examples/index.md
    - Basic: examples/basic.md
    - WebApi: examples/webapi.md
  - Additional resources:
    - Design philosophy: additional-resources/design-philosophy.md
    - Licensing: additional-resources/licensing.md