// Copyright 2025 Xtracked
// SPDX-License-Identifier: GPL-2.0-only OR Commercial

using System.Text.Json.Serialization;
using NodaTime;

namespace WebApi.Models;

/// <summary>Data model of a LEGO set.</summary>
/// <param name="Name">Name of the set.</param>
/// <param name="SetNumber">Set number.</param>
/// <param name="Pieces">Amount of pieces.</param>
/// <param name="Price">Price.</param>
/// <param name="LaunchTime">Date and time on which the set launched.</param>
public sealed record Set(string Name, int SetNumber, int Pieces, double Price, Instant LaunchTime)
{
    /// <summary>ID of this set.</summary>
    /// <remarks>Automatically generated by EFCore.</remarks>
    // Use JsonPropertyOrder '-1' so the 'id' is shown first in the JSON response
    [JsonPropertyOrder(-1)]
    public int Id { get; init; }
}